INSERT INTO products (title, description, category, price, url)
VALUES
  ('Black Bear', 'desc for Black Bear', 'animals', '$500', 'https://i.imgur.com/n4jPBwO.png'),
  ('Butterfly', 'desc for Butterfly', 'animals', '$5', 'https://i.imgur.com/lE2yQ9O.jpg'),
  ('Cow', 'desc for Cow', 'animals', '$200', 'https://i.imgur.com/HbcDOaY.jpg'),
  ('Kitten', 'desc for Kitten', 'animals', '$20', 'https://i.imgur.com/nLllPQ7.jpg'),
  ('Puppy', 'desc for Puppy', 'animals', '$20', 'https://i.imgur.com/dLQXfBS.jpg'),
  ('Raven', 'desc for Raven', 'animals', '$10', 'https://i.imgur.com/ezYivEA.jpg'),
  ('Rooster', 'desc for Rooster', 'animals', '$10', 'https://i.imgur.com/r0e7Ydo.jpg'),
  ('Chair', 'desc for Chair', 'furniture', '$25', 'https://i.imgur.com/2LIzXbO.jpg'),
  ('Chair 2', 'desc for Chair 2', 'furniture', '$25', 'https://i.imgur.com/zxcLlpz.jpg'),
  ('Sofa', 'desc for Sofa', 'furniture', '$100', 'https://i.imgur.com/KGa2QnM.jpg'),
  ('Sofa 2', 'desc for Sofa 2', 'furniture', '$100', 'https://i.imgur.com/5jCF2Z3.jpg'),
  ('Table', 'desc for Table', 'furniture', '$75', 'https://i.imgur.com/2alPKp1.jpg'),
  ('Table 2', 'desc for Table 2', 'furniture', '$75', 'https://i.imgur.com/1nGbnOX.jpg'),
  ('Coffin Bookcase', 'desc for Coffin Bookcase', 'household', '$75', 'https://i.imgur.com/EKJlwAU.jpg'),
  ('Hair Dryer', 'desc for Hair Dryer', 'household', '$20', 'https://i.imgur.com/k25a9kR.jpg'),
  ('Lamp', 'desc for Lamp', 'household', '$15', 'https://i.imgur.com/BY73zrv.jpg'),
  ('Lamp 2', 'desc for Lamp 2', 'household', '$15', 'https://i.imgur.com/7OIRs8q.jpg'),
  ('Salt & Pepper Shakers', 'desc for Salt & Pepper Shakers', 'household', '$10', 'https://i.imgur.com/n3v7SeK.jpg'),
  ('Small Fan', 'desc for nuclear-powered Small Fan', 'household', '$10,000', 'https://i.imgur.com/vuQDVS5.jpg'),
  ('Watch', 'desc for Watch', 'household', '$5,000', 'https://i.imgur.com/AffmtV3.jpg'),
  ('BMW', 'desc for BMW', 'vehicle', '$75,000', 'https://i.imgur.com/JG11eTT.jpg'),
  ('Ferrari', 'desc for Ferrari', 'vehicle', '$250,000', 'https://i.imgur.com/FPZdsXR.jpg'),
  ('Pogo Stick', 'desc for Pogo Stick', 'vehicle', '$100,000', 'https://i.imgur.com/sj6mXQV.jpg'),
  ('Skateboard', 'desc for Skateboard', 'vehicle', '$125,000', 'https://i.imgur.com/NQi69bj.jpg'),
  ('Space Shuttle', 'desc for Space Shuttle', 'vehicle', '$200', 'https://i.imgur.com/lFhrnJu.jpg'),
  ('TIE Fighter', 'desc for TIE Fighter', 'vehicle', '$5,000,000,000', 'https://i.imgur.com/39whCAf.jpg');