CREATE TABLE invoice_products (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS identity,
  invoice_id INTEGER REFERENCES invoices(id),
  product_id INTEGER REFERENCES products(id),
  user_id INTEGER REFERENCES users(id),
  quantity INTEGER NOT null
);